# Generated by Django 5.0.2 on 2024-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userun',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userun',
            name='name',
        ),
        migrations.AddField(
            model_name='userun',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userun',
            name='document_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userun',
            name='document_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userun',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userun',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userun',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userun',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
